name: Docker plus GitHub Actions website deploy
on: push
jobs:
  dockerPlusAction-website-deploy:
    runs-on: ubuntu-latest
    name: Containerise and deploy Website
    steps:
      - name: Hi test
        run: |
          echo "Hi 201 test call"
          date

      - name: Checkout
        uses: actions/checkout@v7

      - name: ssh setup
        run: |
            mkdir -p ~/.ssh
            echo "${{secrets.SSH_PRIVATE_KEY_101}}" > ~/.ssh/myKeys
            chmod 600 ~/.ssh/myKeys
            ssh-keyscan -H ${{secrets.EC2_IP_STG_101}} >> ~/.ssh/known_hosts
              
      - name: install docker on ec2
        run: |
            ssh -i ~/.ssh/myKeys ubuntu@${{secrets.EC2_IP_STG_101}} "sudo apt update && sudo apt install docker.io -y"
            ssh -i ~/.ssh/myKeys ubuntu@${{secrets.EC2_IP_STG_101}} "sudo usermod -aG docker ubuntu"

      - name: copy and deploy website container
        run: |
            scp -i ~/.ssh/myKeys -r frontend ubuntu@${{secrets.EC2_IP_STG_101}}:/home/ubuntu/
            ssh -i ~/.ssh/myKeys ubuntu@${{secrets.EC2_IP}} "docker build -t bt-frontend-image /home/ubuntu/frontend"      
            ssh -i ~/.ssh/myKeys ubuntu@${{secrets.EC2_IP}} "docker stop bt-frontend-container || true"     
            ssh -i ~/.ssh/myKeys ubuntu@${{secrets.EC2_IP}} "docker rm bt-frontend-container || true"  
            ssh -i ~/.ssh/myKeys ubuntu@${{secrets.EC2_IP}} "docker run -d -p 80:80 --name bt-frontend-container bt-frontend-image"   