name: Docker plus GitHub Actions website deploy
on: push
jobs:
  dockerPlusAction-website-deploy:
    runs-on: ubuntu-latest
    name: Containerise and deploy Website
    steps:
      - name: Hi test
        run: |
          echo "Hi 201 test call"
          date