name: Staging Workflow bt
on: push
jobs:
  stg:
    runs-on: ubuntu-latest
    name: Testing 101 just Hi
    steps:
      - name: Hi
        run: |
          echo "Hi 102 test call"
          date

      - name: Post a message in channel (25-09-bt)
        uses: slackapi/slack-github-action@v3.0.3
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_101_BT }}
          webhook-type: incoming-webhook
          payload: |
            text: "... Staging Pipeline started by ${{github.actor}}. Pipeline : ${{github.workflow}} ..🚀"

      - name: ssh setup
        run: |
            mkdir -p ~/.ssh
            echo "${{secrets.SSH_PRIVATE_KEY_101}}" > ~/.ssh/myKeys
            chmod 600 ~/.ssh/myKeys
            ssh-keyscan -H ${{secrets.EC2_IP_STG_101}} >> ~/.ssh/known_hosts
              
      - name: install nginx on ec2
        run: |
            ssh -i ~/.ssh/myKeys ubuntu@${{secrets.EC2_IP_STG_101}} "sudo apt update && sudo apt install nginx -y"

      - name: deploy website
        run: |
            scp -i ~/.ssh/myKeys frontend/index.html ubuntu@${{secrets.EC2_IP_STG_101}}:/home/ubuntu/index.html
            ssh -i ~/.ssh/myKeys ubuntu@${{secrets.EC2_IP_STG_101}} "sudo cp /home/ubuntu/index.html /var/www/html/index.html"

      - name: Post a message in channel (25-09-bt)
        if: ${{ success()}}
        uses: slackapi/slack-github-action@v3.0.3
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_101_BT }}
          webhook-type: incoming-webhook
          payload: |
            text: "✅ Staging Pipeline successfull done! run by ${{github.actor}}. Pipeline : ${{github.workflow}}"  
            
      - name: Post a message in channel (25-09-bt)
        if: ${{ failure()}}
        uses: slackapi/slack-github-action@v3.0.3
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_101_BT }}
          webhook-type: incoming-webhook
          payload: |
            text: "❌ Staging Pipeline failed. Please review!!!."                  
