name: Staging Workflow b
on: push
jobs:
  test101-job:
    runs-on: ubuntu-latest
    name: Testing 101 just Hi
    steps:
      - name: Hi
        run: |
          echo "Hi 102 test call"
          date